services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTG_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - auth-api
      - backend-api

  auth-api:
    build: ./auth-api
    ports:
      - "8000:8000"
    env_file:
      - ./auth-api/.env
    volumes:
      - ./auth-api:/app
    depends_on:
      db:
        condition: service_healthy

  backend-api:
    build: ./backend-api
    ports:
      - "8001:8001"
    env_file:
      - ./backend-api/.env
    volumes:
      - ./backend-api:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: