name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for auth-api
        run: pip install -r auth-api/requirements.txt
      
      - name: Run auth-api tests
        run: pytest auth-api/tests

      - name: Install dependencies for backend-api
        run: pip install -r backend-api/requirements.txt
      
      # You would add tests for the backend-api here as well
      # - name: Run backend-api tests
      #   run: pytest backend-api/tests

  build-and-push-images:
    name: Build and Push Docker Images
    # This job will only run if the 'backend-tests' job is successful
    needs: backend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth-api image
        uses: docker/build-push-action@v5
        with:
          context: ./auth-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-api:latest

      - name: Build and push backend-api image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-api:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest